//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::{entity::prelude::*, sqlx::types::chrono};
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub username: String,
    pub email: String,
    pub password: String,
    pub date_created: DateTime,
    pub date_updated: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::task::Entity")]
    Task,
    #[sea_orm(has_many = "super::user_profile::Entity")]
    UserProfile,
}

impl Related<super::task::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Task.def()
    }
}

impl Related<super::user_profile::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserProfile.def()
    }
}

#[async_trait::async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(self, db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        let now = chrono::Utc::now().naive_utc();

        if insert && self.date_created.is_not_set() {
            let mut this = self;
            this.date_created = sea_orm::ActiveValue::Set(now);
            Ok(this)
        } else if !insert && self.date_updated.is_unchanged() {
            let mut this = self;
            this.date_updated = sea_orm::ActiveValue::Set(Some(now));
            Ok(this)
        } else {
            Ok(self)
        }
    }
}
